import Head from "next/head";
import styles from "../styles/PrivacyPolicy.module.css";

export default function PrivacyPolicy() {
    return (
        <div className={styles.container}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className={styles.main}>
            <h1 className={styles.title}>
            </h1>

          </main>

          <footer className={styles.footer}>
          </footer>
        </div>
}
